-- Create the ud (user data) schema
CREATE SCHEMA IF NOT EXISTS ud;

-- Notebook table
CREATE TABLE IF NOT EXISTS ud.notebook (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    user_id     VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
    modified_at TIMESTAMP
);

-- Note table
CREATE TABLE IF NOT EXISTS ud.note (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    content     TEXT,
    user_id     VARCHAR(255) NOT NULL,
    notebook_id BIGINT REFERENCES ud.notebook(id),
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
    modified_at TIMESTAMP
);

-- Tags table
CREATE TABLE IF NOT EXISTS ud.tags (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

-- Join table for note <-> tag many-to-many
CREATE TABLE IF NOT EXISTS ud.note_tags (
    note_id BIGINT NOT NULL REFERENCES ud.note(id) ON DELETE CASCADE,
    tag_id  BIGINT NOT NULL REFERENCES ud.tags(id) ON DELETE CASCADE,
    PRIMARY KEY (note_id, tag_id)
);

-- AUTH schema 
CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE IF NOT EXISTS auth.users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50)  NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(20)  NOT NULL DEFAULT 'USER',
    enabled  BOOLEAN      NOT NULL DEFAULT TRUE
);

-- Default shared user (password: 'notevault')
INSERT INTO auth.users (username, password, role)
VALUES ('default_user', '$2b$12$r7zVmgFCOonmhYoMjDLbPe0LWJw4cIkLccr/3ZmUs0GZeY7VmkqKa', 'USER')
ON CONFLICT (username) DO NOTHING;
