-- Create the ud (user data) schema
CREATE SCHEMA IF NOT EXISTS ud;

-- Notebook table
CREATE TABLE IF NOT EXISTS ud.notebook (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    user_id     VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
    modified_at TIMESTAMP
);

-- Note table
CREATE TABLE IF NOT EXISTS ud.note (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    content     TEXT,
    user_id     VARCHAR(255) NOT NULL,
    notebook_id BIGINT REFERENCES ud.notebook(id),
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
    modified_at TIMESTAMP
);

-- Tags table
CREATE TABLE IF NOT EXISTS ud.tags (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

-- Join table for note <-> tag many-to-many
CREATE TABLE IF NOT EXISTS ud.note_tags (
    note_id BIGINT NOT NULL REFERENCES ud.note(id) ON DELETE CASCADE,
    tag_id  BIGINT NOT NULL REFERENCES ud.tags(id) ON DELETE CASCADE,
    PRIMARY KEY (note_id, tag_id)
);
